# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ced98dedd4984e7e979c7b99e8eef1e4b00608eca4271c2ca76eac1e62d818050ccbbc8313d9504e862ffc7ae44649d1af86ee5863f58761da2721a42a6a6675

test:
  secret_key_base: 326ac1892fea1ea71fadb475fa0a2cac5606ff88395e7a249a449ad70b2f20e6a64a5b2b138359cbf83d2cbde54b4f19b1dbd125a6988dcf399f68f8f6d1c841

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
